num_agents: 200
dims: 12
steps: 1000
seed: 3
A: 0.3
omega: 0.05
sigma: 0.5
attn_scale: 0.3
layernorm_eps: 1.0e-05
graph_type: watts_strogatz
k_neighbors: 8
rewiring_p: 0.1
evolve_interval: 0
evolve_prob_add: 0.02
evolve_prob_remove: 0.02
bins: 40
device: cpu
